# DOCKER-VERSION 0.3.4 π©lvzhoudev π”√
FROM    h3crd-wlan1.chinacloudapp.cn:5000/tinycore-node:4.4.5 
#FROM    h3crd-wlan1.chinacloudapp.cn:5000/node:6.10.1-alpine

ENV     NODE_ENV production
ENV     WEBSERVER_CONFIG_BDELDEVCONN           false
ENV     WEBSERVER_CONFIG_DEVCONNDELPERIOD      900000
ENV     WEBSERVER_CONFIG_DEVCONNTIMEOUTPERIOD  900000

# The command to exec while docker has been stated
RUN     mkdir -p /workspace
RUN     mkdir -p /workspace/logs
ADD     src  /workspace/src

WORKDIR /workspace/src

EXPOSE  80
EXPOSE  443
EXPOSE  8080
EXPOSE  5858


#CMD sleep 1 && node webserver.js

CMD sleep 1 && npm install -g cnpm --registry=https://registry.npm.taobao.org && cnpm install -g node-inspector && chmod 777 start.sh && ./start.sh && node --expose-gc --debug webserver.js